"""Centralized constants for default settings across the MLX OpenAI Server project."""

from pathlib import Path

DEFAULT_API_HOST = "127.0.0.1"
DEFAULT_AUTO_UNLOAD_MINUTES = None
DEFAULT_BIND_HOST = "0.0.0.0"
DEFAULT_CONFIG_NAME = None
DEFAULT_CONTEXT_LENGTH = 32768
DEFAULT_DISABLE_AUTO_RESIZE = False
DEFAULT_ENABLE_AUTO_TOOL_CHOICE = False
DEFAULT_ENABLE_STATUS_PAGE = True
DEFAULT_GROUP = None
DEFAULT_HUB_CONFIG_PATH = Path.home() / "mlx-openai-server" / "hub.yaml"
DEFAULT_HUB_LOG_PATH = Path.home() / "mlx-openai-server" / "logs"
DEFAULT_IS_DEFAULT_MODEL = False
DEFAULT_JIT_ENABLED = False
DEFAULT_LOG_FILE = None
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_LORA_PATHS_STR = None
DEFAULT_LORA_SCALES_STR = None
DEFAULT_MAX_CONCURRENCY = 1
DEFAULT_MODEL_STARTING_PORT = 47850
DEFAULT_MODEL_TYPE = "lm"
DEFAULT_NO_LOG_FILE = False
DEFAULT_PORT = 8000
DEFAULT_QUANTIZE = 8
DEFAULT_QUEUE_SIZE = 100
DEFAULT_QUEUE_TIMEOUT = 300
DEFAULT_REASONING_PARSER = None
DEFAULT_TOOL_CALL_PARSER = None
DEFAULT_TRUST_REMOTE_CODE = False
HUB_POLL_INTERVAL_SECONDS = 10
